import { Game } from '../shared/models/game.model';

export const castingShadowsMetadata: Game = {
  minPlayers: 2,
  maxPlayers: 4,
  decks: [
    {
      id: 2,
      name: 'Counterspell',
      cards: [
        { name: 'Pointed Shield', count: 4, properties: {"type": ['Reduce Damage'],  } },
        { name: 'Safety Dome', properties: {"type": ['Ignore Damage'],  } },
        { name: 'Bees Everywhere', count: 2, properties: {"type": ['Deal Damage'],  } },
        { name: 'Run Away!', count: 3, properties: {"type": ['Travel'],  } },
      ],
    },
    {
      id: 1,
      name: 'Main',
      cards: [
        { name: 'Red Orb', properties: {"type": ['Resource'], "resource": ['Red Orb'],  } },
        { name: 'Blue Orb', properties: {"type": ['Resource'], "resource": ['Blue Orb'],  } },
        { name: 'Red Gem', count: 3, properties: {"type": ['Resource'], "resource": ['Red Gem'],  } },
        { name: 'Blue Gem', count: 3, properties: {"type": ['Resource'], "resource": ['Blue Gem'],  } },
        { name: 'Infernal Assault', properties: {"type": ['Attack Spell'], "cost": ['Lvl 2 Spell','Shadow Fragment','Red Orb'], "level": ['3'], "attack": ['Enemy'], "range": ['2','Current Tile'], "spell cost": ['Red Gem'],  } },
        { name: 'Sudden Doom', properties: {"type": ['Attack Spell'], "cost": ['Lvl 2 Spell','Shadow Fragment','Blue Orb'], "level": ['3'], "attack": ['Hex Tile'], "range": ['1','Current Tile'], "spell cost": ['Blue Gem'],  } },
        { name: 'Magma Hand', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Red Orb','Shadow Fragment','Gem'], "level": ['2'], "attack": ['Enemy'], "range": ['2','Current Tile'], "spell cost": ['Gem'],  } },
        { name: 'Unicorn Rush', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Orb','Blue Gem'], "level": ['2'], "attack": ['Enemy'], "range": ['1','Current Tile'], "spell cost": ['Blue Gem'],  } },
        { name: 'Deadly Shroud', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Shadow Fragment'], "level": ['2'], "attack": ['Hex Tile'], "range": ['1'], "spell cost": ['Cursed Crystal'],  } },
        { name: 'Personal Space', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Orb'], "level": ['2'], "attack": ['Enemy'], "range": ['Current Tile'],  } },
        { name: 'Psychic Spikes', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Red Orb','Shadow Fragment','Gem'], "level": ['2'], "attack": ['Hex Tile'], "range": ['1'], "spell cost": ['Gem'],  } },
        { name: 'Phoenix Flash', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Orb','Red Gem'], "level": ['2'], "attack": ['Enemy'], "range": ['1','Current Tile'], "spell cost": ['Red Gem'],  } },
        { name: 'Kinetic Wave', properties: {"type": ['Attack Spell'], "cost": ['Lvl 1 Spell','Blue Orb','Shadow Fragment','Gem'], "level": ['2'], "attack": ['Hex Tile'], "range": ['2'], "spell cost": ['Blue Gem'],  } },
        { name: 'Orb Duplication', properties: {"type": ['Conversion Spell'], "cost": ['Lvl 1 Spell','Orb'], "resource": ['Orb'], "level": ['2'], "spell cost": ['Orb'],  } },
        { name: 'Gem Duplication', properties: {"type": ['Conversion Spell'], "cost": ['Lvl 1 Spell','Gem'], "resource": ['Gem'], "level": ['2'], "spell cost": ['Gem'],  } },
        { name: 'Fatal Fronds', count: 4, properties: {"type": ['Attack Spell'], "cost": ['Orb'], "level": ['1'], "attack": ['Hex Tile'], "range": ['Current Tile'],  } },
        { name: 'Feeding Frenzy', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Blue Orb','Blue Gem'], "level": ['1'], "attack": ['Enemy'], "range": ['1','Current Tile'], "spell cost": ['Blue Gem'],  } },
        { name: 'Bubble Trouble', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Blue Orb','Blue Gem'], "level": ['1'], "attack": ['Enemy'], "range": ['1'], "spell cost": ['Blue Gem'],  } },
        { name: 'Heat Wave', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Red Orb',' Red Gem'], "level": ['1'], "attack": ['Enemy'], "range": ['1'], "spell cost": ['Red Gem'],  } },
        { name: 'Spectral Slap', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Blue Orb','Gem'], "level": ['1'], "attack": ['Hex Tile'], "range": ['1'], "spell cost": ['Red Gem','Blue Gem'],  } },
        { name: 'Heavy Hand', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Red Orb',' Red Gem'], "level": ['1'], "attack": ['Enemy'], "range": ['1','Current Tile'], "spell cost": ['Red Gem'],  } },
        { name: 'Lightning Bug', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Orb','Gem'], "level": ['1'], "attack": ['Enemy'], "range": ['1'], "spell cost": ['Gem'],  } },
        { name: 'Sinister Screech', count: 3, properties: {"type": ['Attack Spell'], "cost": ['Shadow Fragment','Orb'], "level": ['1'], "attack": ['Enemy'], "range": ['1'], "spell cost": ['Cursed Crystal'],  } },
        { name: 'Curse Void', count: 2, properties: {"type": ['Conversion Spell'], "cost": ['Shadow Fragment','Gem'], "resource": ['Gem'], "level": ['1'], "spell cost": ['Cursed Crystal'],  } },
        { name: 'Metamorphosis', properties: {"type": ['Conversion Spell'], "cost": ['Orb'], "resource": ['Orb'], "level": ['1'], "spell cost": ['Orb'],  } },
        { name: 'Crystallization', properties: {"type": ['Conversion Spell'], "cost": ['Blue Orb','Red Gem'], "resource": ['Orb'], "level": ['1'], "spell cost": ['Gem'],  } },
        { name: 'Energy Bloom', properties: {"type": ['Conversion Spell'], "cost": ['Gem'], "resource": ['Gem'], "level": ['1'], "spell cost": ['Gem'],  } },
        { name: 'Sapphire Synthesis', properties: {"type": ['Conversion Spell'], "cost": ['Orb','Blue Gem'], "resource": ['Blue Gem','Blue Orb'], "level": ['1'], "spell cost": ['Blue Gem','Blue Orb'],  } },
        { name: 'Ruby Synthesis', properties: {"type": ['Conversion Spell'], "cost": ['Orb','Red Gem'], "resource": ['Red Gem','Red Orb'], "level": ['1'], "spell cost": ['Red Gem','Red Orb'],  } },
        { name: 'Luminous Glow', properties: {"type": ['Conversion Spell'], "cost": ['Red Orb','Blue Gem'], "resource": ['Gem'], "level": ['1'], "spell cost": ['Orb'],  } },
      ],
    },
  ],
  expansions: [],
  diceSets: [
    {
      dice: [
        {
          type: 'fancy',
          sides: [
            'Blue Gem',
            'Blue Gem',
            'Blue Orb',
            'Blue Orb',
            'Cursed Crystal',
            'Shadow Fragment',
          ],
        },
        {
          type: 'fancy',
          sides: [
            'Blue Gem',
            'Blue Gem',
            'Blue Orb',
            'Blue Orb',
            'Cursed Crystal',
            'Shadow Fragment',
          ],
        },
        {
          type: 'fancy',
          sides: [
            'Red Gem',
            'Red Gem',
            'Red Orb',
            'Red Orb',
            'Cursed Crystal',
            'Shadow Fragment',
          ],
        },
        {
          type: 'fancy',
          sides: [
            'Red Gem',
            'Red Gem',
            'Red Orb',
            'Red Orb',
            'Cursed Crystal',
            'Shadow Fragment',
          ],
        },
        {
          type: 'fancy',
          sides: [
            'Purple Gem',
            'Purple Gem',
            'Purple Orb',
            'Purple Orb',
            'Cursed Crystal',
            'Shadow Fragment',
          ],
        },
      ],
    },
  ],
};
