import { Game } from '../shared/models/game.model';

export const doomlingsMetadata: Game = {
  minPlayers: 2,
  maxPlayers: 6,
  expansions: [
    { id: 1, name: 'Kickstarter' },
    { id: 2, name: 'Kickstarter Stretch' },
    { id: 3, name: 'Multi-Color' },
    { id: 4, name: 'Dinolings' },
    { id: 5, name: 'Mythlings' },
    { id: 6, name: 'Techlings' },
    { id: 7, name: 'The Meaning of Life' },
  ],
  decks: [
    {
      id: 1,
      name: 'Traits',
      pick: 1,
      pickMax: 8,
      cards: [
        { name: 'Echolocation', properties: {"color": ['Blue'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Immunity', properties: {"color": ['Blue'], "points": ['4'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Tiny', properties: {"color": ['Blue'], "points": ['17'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Automimicry', properties: {"color": ['Blue'], "points": ['0'], "effect": ['Action'],  } },
        { name: 'Blubber', properties: {"color": ['Blue'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Chromatophores', properties: {"color": ['Blue'], "points": ['0'], "effect": ['Out of Turn Action'],  } },
        { name: 'Cold Blood', properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Costly Signaling', properties: {"color": ['Blue'], "points": ['-2'], "effect": ['Action'],  } },
        { name: 'Egg Clusters', properties: {"color": ['Blue'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Flight', properties: {"color": ['Blue'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Gills', properties: {"color": ['Blue'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Iridescent Scales', properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Migratory', properties: {"color": ['Blue'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Painted Shell', properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Regenerative Tissue', properties: {"color": ['Blue'], "points": ['0'], "effect": ['Trait'],  } },
        { name: 'Saliva', properties: {"color": ['Blue'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Selective Memory', properties: {"color": ['Blue'], "points": ['0'], "effect": ['Action'],  } },
        { name: 'Spiny', properties: {"color": ['Blue'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Sweat', properties: {"color": ['Blue'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Tentacles', properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Scutes', properties: {"color": ['Blue'], "points": ['3'], "effect": ['Action'],  } },
        { name: 'Heroic', properties: {"color": ['Green'], "points": ['7'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Pack Behavior', properties: {"color": ['Green'], "points": ['3'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Symbiosis', properties: {"color": ['Green'], "points": ['3'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Appealing', properties: {"color": ['Green'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Bark', properties: {"color": ['Green'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Branches', properties: {"color": ['Green'], "points": ['0'], "effect": ['Scoring'],  } },
        { name: 'Deep Roots', properties: {"color": ['Green'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Fecundity', properties: {"color": ['Green'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Fortunate', properties: {"color": ['Green'], "points": ['1'], "effect": ['Scoring'],  } },
        { name: 'Leaves', properties: {"color": ['Green'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Overgrowth', properties: {"color": ['Green'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Photosynthesis', properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Pollination', properties: {"color": ['Green'], "points": ['1'], "effect": ['Scoring'],  } },
        { name: 'Propagation', properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Random Fertilization', properties: {"color": ['Green'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Self-Replicating', properties: {"color": ['Green'], "points": ['0'], "effect": ['Action'],  } },
        { name: 'Swarm', count: 6, properties: {"color": ['Green'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Tiny Little Melons', properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Trunk', properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Woody Stems', properties: {"color": ['Green'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Denial', properties: {"color": ['Gray'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Faith', properties: {"color": ['Gray'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Optimistic Nihilism', properties: {"color": ['Gray'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Altruistic', properties: {"color": ['Gray'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Boredom', properties: {"color": ['Gray'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Confusion', properties: {"color": ['Gray'], "points": ['-2'], "effect": ['none'],  } },
        { name: 'Delicious', properties: {"color": ['Gray'], "points": ['4'], "effect": ['Trait'],  } },
        { name: 'Doting', properties: {"color": ['Gray'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Eloquance', properties: {"color": ['Gray'], "points": ['1'], "effect": ['World\'s End'],  } },
        { name: 'Fear', properties: {"color": ['Gray'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Flatulence', properties: {"color": ['Gray'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Gratitude', properties: {"color": ['Gray'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Introspective', properties: {"color": ['Gray'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Just', properties: {"color": ['Gray'], "points": ['2'], "effect": ['Trait'],  } },
        { name: 'Late', properties: {"color": ['Gray'], "points": ['1'], "effect": ['Out of Turn Action'],  } },
        { name: 'Mindful', properties: {"color": ['Gray'], "points": ['0'], "effect": ['Scoring'],  } },
        { name: 'Mitochondrion', properties: {"color": ['Gray'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Morality', properties: {"color": ['Gray'], "points": ['5'], "effect": ['Trait'],  } },
        { name: 'Prepper', properties: {"color": ['Gray'], "points": ['2'], "effect": ['World\'s End'],  } },
        { name: 'Saudade', properties: {"color": ['Gray'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Self-Awareness', properties: {"color": ['Gray'], "points": ['-1'], "effect": ['Out of Turn Action'],  } },
        { name: 'The Third Eye', properties: {"color": ['Gray'], "points": ['0'], "effect": ['Action'],  } },
        { name: 'Camouflage', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Vampirism', properties: {"color": ['Purple'], "points": ['3'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Viral', properties: {"color": ['Purple'], "points": ['2'], "effect": ['World\'s End','Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Adorable', properties: {"color": ['Purple'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Big Ears', properties: {"color": ['Purple'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Clever', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Directly Register', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Dreamer', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Fine Motor Skills', properties: {"color": ['Purple'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Impatience', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Inventive', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Memory', properties: {"color": ['Purple'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Nocturnal', properties: {"color": ['Purple'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Nosy', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Parasitic', properties: {"color": ['Purple'], "points": ['-2'], "effect": ['Out of Turn Action'],  } },
        { name: 'Persuasive', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Poisonous', properties: {"color": ['Purple'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Selfish', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Sneaky', properties: {"color": ['Purple'], "points": ['2'], "effect": ['World\'s End','Out of Turn Action'],  } },
        { name: 'Sticky Secretions', properties: {"color": ['Purple'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Super Spreader', properties: {"color": ['Purple'], "points": ['2'], "effect": ['Trait'],  } },
        { name: 'Teeth', properties: {"color": ['Purple'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Telekinetic', properties: {"color": ['Purple'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Venomous', properties: {"color": ['Purple'], "points": ['-2'], "effect": ['Action'],  } },
        { name: 'Apex Predator', properties: {"color": ['Red'], "points": ['4'], "effect": ['Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Hyper-Inetelligence', properties: {"color": ['Red'], "points": ['4'], "effect": ['World\'s End'], "Dominant": ['Yes'],  } },
        { name: 'Sentience', properties: {"color": ['Red'], "points": ['2'], "effect": ['World\'s End','Scoring'], "Dominant": ['Yes'],  } },
        { name: 'Antlers', properties: {"color": ['Red'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Bad', properties: {"color": ['Red'], "points": ['3'], "effect": ['Action'],  } },
        { name: 'Brave', properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Brute Strength', properties: {"color": ['Red'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Endurance', properties: {"color": ['Red'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Fangs', properties: {"color": ['Red'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Fire Skin', properties: {"color": ['Red'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Heat Vision', properties: {"color": ['Red'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Hot Temper', properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Kidney', count: 5, properties: {"color": ['Red'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Quick', properties: {"color": ['Red'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Reckless', properties: {"color": ['Red'], "points": ['3'], "effect": ['Action'],  } },
        { name: 'Retractible Claws', properties: {"color": ['Red'], "points": ['5'], "effect": ['Trait'],  } },
        { name: 'Stone Skin', properties: {"color": ['Red'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Territorial', properties: {"color": ['Red'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Voracious', properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Warm Blood', properties: {"color": ['Red'], "points": ['-1'], "effect": ['Trait'],  } },
        { name: 'Fulfilled', expansionId: 1, properties: {"color": ['Yellow'], "points": ['4'], "effect": ['Trait'],  } },
        { name: 'Motley', expansionId: 1, properties: {"color": ['Blue','Green','Purple','Red'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Tube Feet', expansionId: 2, properties: {"color": ['Blue'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Beauty', expansionId: 2, properties: {"color": ['Green'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Bones', expansionId: 2, properties: {"color": ['Gray'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Juicy', expansionId: 2, properties: {"color": ['Purple'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Pride', expansionId: 2, properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Tetrachromatic', expansionId: 1, properties: {"color": ['Purple'], "points": ['4'], "effect": ['Scoring'],  } },
        { name: 'Wild', expansionId: 3, properties: {"color": ['Blue','Green','Purple','Red'], "points": ['4'], "effect": ['none'], "Dominant": ['Yes'],  } },
        { name: 'Mitosis', expansionId: 3, properties: {"color": ['Blue','Purple'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Free Will', expansionId: 3, properties: {"color": ['Gray'], "points": ['2'], "effect": ['World\'s End'],  } },
        { name: 'Hand-Wing', expansionId: 3, properties: {"color": ['Red','Purple'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Curiosity', expansionId: 3, properties: {"color": ['Blue','Red'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Bullheaded', expansionId: 3, properties: {"color": ['Red','Green'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Bloom', expansionId: 3, properties: {"color": ['Blue','Green'], "points": ['1'], "effect": ['none'],  } },
        { name: 'Acrobatic', expansionId: 3, properties: {"color": ['Green','Purple'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Elongated Neck', expansionId: 4, properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Pterosaur Wings', expansionId: 4, properties: {"color": ['Blue'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Terror Beak', expansionId: 4, properties: {"color": ['Blue'], "points": ['3'], "effect": ['Trait'],  } },
        { name: 'Bony Plates', expansionId: 4, properties: {"color": ['Green'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Ceratopsian Horns', expansionId: 4, properties: {"color": ['Green'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Fronds', expansionId: 4, properties: {"color": ['Green'], "points": ['0'], "effect": ['Trait'],  } },
        { name: 'Thagomizer', expansionId: 4, properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Cranial Crest', expansionId: 4, properties: {"color": ['Gray'], "points": ['4'], "effect": ['Scoring'],  } },
        { name: 'Dermal Armor', expansionId: 4, properties: {"color": ['Gray'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Pycnofibers', expansionId: 4, properties: {"color": ['Gray'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Egg Predation', expansionId: 4, properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Protofeathers', expansionId: 4, properties: {"color": ['Purple'], "points": ['-2'], "effect": ['Action'],  } },
        { name: 'Talons', expansionId: 4, properties: {"color": ['Purple'], "points": ['2'], "effect": ['none'],  } },
        { name: 'Carnosaur Jaw', expansionId: 4, properties: {"color": ['Red'], "points": ['9'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Serrated Teeth', expansionId: 4, properties: {"color": ['Red'], "points": ['5'], "effect": ['Scoring'],  } },
        { name: 'Tiny Arms', expansionId: 4, properties: {"color": ['Red'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Legendary', expansionId: 5, properties: {"color": ['Blue'], "points": ['8'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Diaphanous Wings', expansionId: 5, properties: {"color": ['Blue'], "points": ['-1'], "effect": ['none'],  } },
        { name: 'Icy', expansionId: 5, properties: {"color": ['Blue'], "points": ['3'], "effect": ['none'],  } },
        { name: 'Righteous', expansionId: 5, properties: {"color": ['Blue'], "points": ['1'], "effect": ['Out of Turn Action'],  } },
        { name: 'Elven Ears', expansionId: 5, properties: {"color": ['Green'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Fey', expansionId: 5, properties: {"color": ['Green'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Orcish Tusks', expansionId: 5, properties: {"color": ['Green'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Destined', expansionId: 5, properties: {"color": ['Gray'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Effigial', expansionId: 5, properties: {"color": ['Gray'], "points": ['-3'], "effect": ['Out of Turn Action'],  } },
        { name: 'Rainbow Horn', expansionId: 5, properties: {"color": ['Gray'], "points": ['2'], "effect": ['World\'s End'],  } },
        { name: 'Necromantic', expansionId: 5, properties: {"color": ['Purple'], "points": ['1'], "effect": ['Out of Turn Action'],  } },
        { name: 'Witchy', expansionId: 5, properties: {"color": ['Purple'], "points": ['2'], "effect": ['Out of Turn Action'],  } },
        { name: 'Zombified', expansionId: 5, properties: {"color": ['Purple'], "points": ['-2'], "effect": ['Out of Turn Action'],  } },
        { name: 'Ancient', expansionId: 5, properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Dragon Heart', expansionId: 5, properties: {"color": ['Red'], "points": ['1'], "effect": ['Scoring'],  } },
        { name: 'Gelatinous', expansionId: 5, properties: {"color": ['Red'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Mighty', expansionId: 5, properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Cybernetic', expansionId: 6, properties: {"color": ['Blue'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Mecha', expansionId: 6, properties: {"color": ['Blue'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Neural Link', expansionId: 6, properties: {"color": ['Blue'], "points": ['2'], "effect": ['Action'],  } },
        { name: 'Lyonization', expansionId: 6, properties: {"color": ['Green'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Nano', expansionId: 6, properties: {"color": ['Green'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Transgenic Modification', expansionId: 6, properties: {"color": ['Green'], "points": ['1'], "effect": ['Trait'],  } },
        { name: 'Ruggedized', expansionId: 6, properties: {"color": ['Gray'], "points": ['4'], "effect": ['Trait'], "Dominant": ['Yes'],  } },
        { name: 'Binary', expansionId: 6, properties: {"color": ['Gray'], "points": ['0'], "effect": ['Action'],  } },
        { name: 'GMO', expansionId: 6, properties: {"color": ['Gray'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Grey Hat', expansionId: 6, properties: {"color": ['Gray'], "points": ['-1'], "effect": ['Action'],  } },
        { name: 'Electromagnetic', expansionId: 6, properties: {"color": ['Purple'], "points": ['1'], "effect": ['Action'],  } },
        { name: 'Hypermyelination', expansionId: 6, properties: {"color": ['Purple'], "points": ['star'], "effect": ['Scoring'],  } },
        { name: 'Subdermal Plating', expansionId: 6, properties: {"color": ['Purple'], "points": ['-1'], "effect": ['Out of Turn Action'],  } },
        { name: 'Bionic Arm', expansionId: 6, properties: {"color": ['Red'], "points": ['-1'], "effect": ['Scoring'],  } },
        { name: 'Bone Reinforcement', expansionId: 6, properties: {"color": ['Red'], "points": ['4'], "effect": ['none'],  } },
        { name: 'Phreakish Eyes', expansionId: 6, properties: {"color": ['Red'], "points": ['2'], "effect": ['Action'],  } },
      ],
    },
    {
      id: 1,
      name: 'Ages',
      cards: [
 
      ],
    },
  ],
  diceSets: [
  ],
};
