import { Game } from '../shared/models/game.model';

export const hereToSlayMetadata: Game = {
  minPlayers: 0,
  maxPlayers: 0,
  expansions: [{ id: 1, name: 'Warriors & Druids' }],
  decks: [
    {
      id: 1,
      name: 'Main',
      pick: 1,
      pickMax: 5,
      cards: [
        { name: 'Challenge', count: 14, properties: {"type": ['Challenge'],  } },
        { name: 'Modifier', count: 4, properties: {"type": ['Modifier'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Modifier', count: 4, properties: {"type": ['Modifier'], "modifier": ['-'], "effect": ['MODIFIER'],  } },
        { name: 'Modifier', count: 17, properties: {"type": ['Modifier'], "modifier": ['+','-'], "effect": ['MODIFIER'],  } },
        { name: 'Suspiciously Shiny Coin', properties: {"type": ['Cursed Item'], "effect": ['DISCARD'],  } },
        { name: 'Curse of the Snake\'s Eyes', count: 2, properties: {"type": ['Cursed Item'], "modifier": ['-'], "effect": ['MODIFIER'],  } },
        { name: 'Sealing Key', properties: {"type": ['Cursed Item'],  } },
        { name: 'Particularly Rusty Coin', count: 2, properties: {"type": ['Item'], "effect": ['DRAW'],  } },
        { name: 'Really Big Ring', count: 2, properties: {"type": ['Item'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Decoy Doll', properties: {"type": ['Item'], "effect": ['SACRIFICE','DESTROY'],  } },
        { name: 'Ranger Mask', properties: {"type": ['Item'], "hero": ['Ranger'],  } },
        { name: 'Guardian Mask', properties: {"type": ['Item'], "hero": ['Guardian'],  } },
        { name: 'Wizard Mask', properties: {"type": ['Item'], "hero": ['Wizard'],  } },
        { name: 'Fighter Mask', properties: {"type": ['Item'], "hero": ['Fighter'],  } },
        { name: 'Bard Mask', properties: {"type": ['Item'], "hero": ['Bard'],  } },
        { name: 'Thief Mask', properties: {"type": ['Item'], "hero": ['Thief'],  } },
        { name: 'Winds of Change', count: 2, properties: {"type": ['Magic'], "effect": ['DRAW'],  } },
        { name: 'Destructive Spell', count: 2, properties: {"type": ['Magic'], "effect": ['DISCARD','DESTROY'],  } },
        { name: 'Entangling Trap', count: 2, properties: {"type": ['Magic'], "effect": ['DISCARD','STEAL'],  } },
        { name: 'Enchanted Spell', count: 2, properties: {"type": ['Magic'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Critical Boost', count: 2, properties: {"type": ['Magic'], "effect": ['DRAW','DISCARD'],  } },
        { name: 'Forceful Winds', properties: {"type": ['Magic'],  } },
        { name: 'Call to the Fallen', properties: {"type": ['Magic'],  } },
        { name: 'Forced Exchange', properties: {"type": ['Magic'], "effect": ['STEAL'],  } },
        { name: 'Fuzzy Cheeks', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['8+'],  } },
        { name: 'Lucky Bucky', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['7+'],  } },
        { name: 'Dodgy Dealer', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['9+'],  } },
        { name: 'Tipsy Tootie', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['STEAL'], "Roll": ['6+'],  } },
        { name: 'Peanut', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['7+'],  } },
        { name: 'Mellow Dee', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['7+'],  } },
        { name: 'Greedy Cheeks', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['8+'],  } },
        { name: 'Napping Nibbles', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['2+'],  } },
        { name: 'Tough Teddy', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['4+'],  } },
        { name: 'Qi Bear', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD','DESTROY'], "Roll": ['10+'],  } },
        { name: 'Heavy Bear', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['5+'],  } },
        { name: 'Fury Knuckle', properties: {"type": ['Hero'], "hero": ['Fighter'], "Roll": ['5+'],  } },
        { name: 'Bad Axe', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DESTROY'], "Roll": ['8+'],  } },
        { name: 'Bear Claw', properties: {"type": ['Hero'], "hero": ['Fighter'], "Roll": ['7+'],  } },
        { name: 'Pan Chucks', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DRAW','DESTROY'], "Roll": ['8+'],  } },
        { name: 'Beary Wise', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['7+'],  } },
        { name: 'Serious Grey', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DESTROY'], "Roll": ['9+'],  } },
        { name: 'Sharp Fox', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['5+'],  } },
        { name: 'Quick Draw', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['8+'],  } },
        { name: 'Wildshot', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW','DISCARD'], "Roll": ['8+'],  } },
        { name: 'Bullseye', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['7+'],  } },
        { name: 'Lookie Rookie', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['5+'],  } },
        { name: 'Hook', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['6+'],  } },
        { name: 'Wily Red', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['10+'],  } },
        { name: 'Smooth Mimimeow', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['7+'],  } },
        { name: 'Meowzio', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['STEAL'], "Roll": ['10+'],  } },
        { name: 'Sly Pickings', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['6+'],  } },
        { name: 'Plundering Puma', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DRAW'], "Roll": ['6+'],  } },
        { name: 'Shurikitty', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DESTROY'], "Roll": ['9+'],  } },
        { name: 'Slippery Paws', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DISCARD'], "Roll": ['6+'],  } },
        { name: 'Silent Shadow', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['8+'],  } },
        { name: 'Kit Napper', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['STEAL'], "Roll": ['9+'],  } },
        { name: 'Hopper', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['SACRIFICE'], "Roll": ['7+'],  } },
        { name: 'Bun Bun', properties: {"type": ['Hero'], "hero": ['Wizard'], "Roll": ['5+'],  } },
        { name: 'Spooky', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['SACRIFICE'], "Roll": ['10+'],  } },
        { name: 'Buttons', properties: {"type": ['Hero'], "hero": ['Wizard'], "Roll": ['6+'],  } },
        { name: 'Wiggles', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['STEAL'], "Roll": ['10+'],  } },
        { name: 'Fluffy', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['DESTROY'], "Roll": ['10+'],  } },
        { name: 'Snowball', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['DRAW'], "Roll": ['6+'],  } },
        { name: 'Whiskers', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['STEAL','DESTROY'], "Roll": ['11+'],  } },
        { name: 'Calming Voice', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['9+'],  } },
        { name: 'Mighty Blade', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['8+'],  } },
        { name: 'Vibrant Glow', properties: {"type": ['Hero'], "hero": ['Guardian'], "modifier": ['+'], "effect": ['MODIFIER'], "Roll": ['9+'],  } },
        { name: 'Wise Shield', properties: {"type": ['Hero'], "hero": ['Guardian'], "modifier": ['+'], "effect": ['MODIFIER'], "Roll": ['6+'],  } },
        { name: 'Iron Resolve', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['8+'],  } },
        { name: 'Guiding Light', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['7+'],  } },
        { name: 'Radiant Horn', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['6+'],  } },
        { name: 'Holy Curselifter', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['5+'],  } },
      ],
    },
    {
      id: 2,
      name: 'Monster Cards',
      pick: 1,
      pickMax: 3,
      cards: [
      { name: 'Malamammoth', properties: {"hero count": ['2'], "hero": ['Ranger'], "effect": ['DRAW'], "Slay": ['8+'],  } },
      { name: 'Dracos', properties: {"hero count": ['1'], "effect": ['DRAW'], "Slay": ['5-'],  } },
      { name: 'Warworn Owlbear', properties: {"hero count": ['2'], "hero": ['Thief'], "Slay": ['8+'],  } },
      { name: 'Bloodwing', properties: {"hero count": ['2'], "effect": ['CHALLENGE','DISCARD'], "Slay": ['9+'],  } },
      { name: 'Crowned Serpent', properties: {"hero count": ['2'], "effect": ['DRAW'], "Slay": ['10+'],  } },
      { name: 'Dark Dragon King', properties: {"hero count": ['2'], "hero": ['Bard'], "modifier": ['+'], "effect": ['MODIFIER'], "Slay": ['8+'],  } },
      { name: 'Corrupted Sabretooth', properties: {"hero count": ['3'], "effect": ['DESTROY','STEAL'], "Slay": ['9+'],  } },
      { name: 'Abyss Queen', properties: {"hero count": ['2'], "modifier": ['+'], "effect": ['MODIFIER'], "Slay": ['8+'],  } },
      { name: 'Artic Aries', properties: {"hero count": ['1'], "effect": ['DRAW'], "Slay": ['10+'],  } },
      { name: 'Terratuga', properties: {"hero count": ['1'], "Slay": ['11+'],  } },
      { name: 'Anuran Cauldron', properties: {"hero count": ['3'], "modifier": ['+'], "effect": ['MODIFIER'], "Slay": ['7+'],  } },
      { name: 'Rex Major', properties: {"hero count": ['2'], "hero": ['Guardian'], "effect": ['DRAW'], "Slay": ['8+'],  } },
      { name: 'Orthus', properties: {"hero count": ['2'], "hero": ['Wizard'], "effect": ['DRAW'], "Slay": ['8+'],  } },
      { name: 'Titan Wyvern', properties: {"hero count": ['2'], "hero": ['Fighter'], "modifier": ['+'], "effect": ['MODIFIER'], "Slay": ['8+'],  } },
      { name: 'Mega Slime', properties: {"hero count": ['4'], "Slay": ['8+'],  } },
      ],
    },
    {
      id: 1,
      name: 'Warriors & Druids',
      expansionId: 1,
      cards: [
        { name: 'Druid Challenge', properties: {"type": ['Challenge'], "hero": ['Druid'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Warrior Challenge', properties: {"type": ['Challenge'], "hero": ['Warrior'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Modifier', properties: {"type": ['Modifier'], "modifier": ['+'], "effect": ['MODIFIER','DRAW'],  } },
        { name: 'Modifier', properties: {"type": ['Modifier'], "modifier": ['-'], "effect": ['MODIFIER'],  } },
        { name: 'Modifier', count: 2, properties: {"type": ['Modifier'], "modifier": ['+','-'], "effect": ['MODIFIER','DRAW'],  } },
        { name: 'Soul Tether', properties: {"type": ['Cursed Item'], "effect": ['SACRIFICE'],  } },
        { name: 'Cursed Glove', properties: {"type": ['Cursed Item'],  } },
        { name: 'Temproal Hourglass', properties: {"type": ['Item'],  } },
        { name: 'Even Bigger Ring', properties: {"type": ['Item'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Bottomless Bag', properties: {"type": ['Item'],  } },
        { name: 'Warrior Mask', properties: {"type": ['Item'], "hero": ['Warrior'],  } },
        { name: 'Druid Mask', properties: {"type": ['Item'], "hero": ['Druid'],  } },
        { name: 'Rapid Refresh', properties: {"type": ['Magic'], "effect": ['DISCARD','DRAW'],  } },
        { name: 'Beast Call', properties: {"type": ['Magic'],  } },
        { name: 'Stagguard', properties: {"type": ['Hero'], "hero": ['Druid'], "Roll": ['8-'],  } },
        { name: 'Maegisty', properties: {"type": ['Hero'], "hero": ['Druid'], "Roll": ['7-'],  } },
        { name: 'Glowing Antler', properties: {"type": ['Hero'], "hero": ['Druid'], "Roll": ['7-'],  } },
        { name: 'Big Buckley', properties: {"type": ['Hero'], "hero": ['Druid'], "effect": ['ATTACK'], "Roll": ['8-'],  } },
        { name: 'Magus Moose', properties: {"type": ['Hero'], "hero": ['Druid'], "Roll": ['5-'],  } },
        { name: 'Majestelk', properties: {"type": ['Hero'], "hero": ['Druid'], "modifier": ['+','-'], "effect": ['SACRIFICE','MODIFIER'], "Roll": ['7-'],  } },
        { name: 'Doe Fallow', properties: {"type": ['Hero'], "hero": ['Druid'], "effect": ['SACRIFICE','DRAW'], "Roll": ['7-'],  } },
        { name: 'Buck Omens', properties: {"type": ['Hero'], "hero": ['Druid'], "Roll": ['6-'],  } },
        { name: 'Silent Shield', properties: {"type": ['Hero'], "hero": ['Warrior'], "effect": ['SACRIFICE','DESTROY'], "Roll": ['6+'],  } },
        { name: 'Tenacious Timber', properties: {"type": ['Hero'], "hero": ['Warrior'], "effect": ['STEAL'], "Roll": ['8+'],  } },
        { name: 'Wolfgang Pack', properties: {"type": ['Hero'], "hero": ['Warrior'], "modifier": ['+'], "effect": ['MODIFIER'], "Roll": ['5+'],  } },
        { name: 'Hardened Hunter', properties: {"type": ['Hero'], "hero": ['Warrior'], "effect": ['DRAW'], "Roll": ['9+'],  } },
        { name: 'Blinding Blade', properties: {"type": ['Hero'], "hero": ['Warrior'], "Roll": ['8+'],  } },
        { name: 'Critical Fang', properties: {"type": ['Hero'], "hero": ['Warrior'], "modifier": ['+'], "effect": ['ATTACK','MODIFIER'], "Roll": ['6+'],  } },
        { name: 'Looting Lupo', properties: {"type": ['Hero'], "hero": ['Warrior'], "effect": ['DRAW'], "Roll": ['5+'],  } },
        { name: 'Agile Dagger', properties: {"type": ['Hero'], "hero": ['Warrior'], "Roll": ['7+'],  } },
      ],
    },
    {
      id: 2,
      name: 'Warriors & Druids',
      expansionId: 1,
      cards: [
        { name: 'Feral Dragon', properties: {"hero count": ['2'], "effect": ['DRAW'], "Slay": ['9+'],  } },
        { name: 'Muscipula Rex', properties: {"hero count": ['3'], "effect": ['DRAW'], "Slay": ['10+'],  } },
      ]
    }
  ],
  diceSets: [
    {
      dice: [{ type: 'd6' }, { type: 'd6' }],
    },
  ],
};
