import { Game } from '../shared/models/game.model';

export const hereToSlayMetadata: Game = {
  minPlayers: 0,
  maxPlayers: 0,
  expansions: [{ id: 1, name: 'Warriors & Druids' }],
  decks: [
    {
      id: 1,
      name: 'Main',
      pick: 1,
      pickMax: 5,
      cards: [
        { name: 'Challenge', count: 14, properties: {"type": ['Challenge'],  } },
        { name: 'Modifier', count: 4, properties: {"type": ['Modifier'], "modifier": ['+'],  } },
        { name: 'Modifier', count: 4, properties: {"type": ['Modifier'], "modifier": ['-'],  } },
        { name: 'Modifier', count: 17, properties: {"type": ['Modifier'], "modifier": ['+','-'],  } },
        { name: 'Suspiciously Shiny Coin', properties: {"type": ['Cursed Item'], "effect": ['DISCARD'],  } },
        { name: 'Curse of the Snake\'s Eyes', count: 2, properties: {"type": ['Cursed Item'], "modifier": ['-'], "effect": ['MODIFIER'],  } },
        { name: 'Sealing Key', properties: {"type": ['Cursed Item'],  } },
        { name: 'Particularly Rusty Coin', count: 2, properties: {"type": ['Item'], "effect": ['DRAW'],  } },
        { name: 'Really Big Ring', count: 2, properties: {"type": ['Item'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Decoy Doll', properties: {"type": ['Item'], "effect": ['SACRIFICE','DESTROY'],  } },
        { name: 'Ranger Mask', properties: {"type": ['Item'], "hero": ['Ranger'],  } },
        { name: 'Guardian Mask', properties: {"type": ['Item'], "hero": ['Guardian'],  } },
        { name: 'Wizard Mask', properties: {"type": ['Item'], "hero": ['Wizard'],  } },
        { name: 'Fighter Mask', properties: {"type": ['Item'], "hero": ['Fighter'],  } },
        { name: 'Bard Mask', properties: {"type": ['Item'], "hero": ['Bard'],  } },
        { name: 'Thief Mask', properties: {"type": ['Item'], "hero": ['Thief'],  } },
        { name: 'Winds of Change', count: 2, properties: {"type": ['Magic'], "effect": ['DRAW'],  } },
        { name: 'Destructive Spell', count: 2, properties: {"type": ['Magic'], "effect": ['DISCARD','DESTROY'],  } },
        { name: 'Entangling Trap', count: 2, properties: {"type": ['Magic'], "effect": ['DISCARD','STEAL'],  } },
        { name: 'Enchanted Spell', count: 2, properties: {"type": ['Magic'], "modifier": ['+'], "effect": ['MODIFIER'],  } },
        { name: 'Critical Boost', count: 2, properties: {"type": ['Magic'], "effect": ['DRAW','DISCARD'],  } },
        { name: 'Forceful Winds', properties: {"type": ['Magic'],  } },
        { name: 'Call to the Fallen', properties: {"type": ['Magic'],  } },
        { name: 'Forced Exchange', properties: {"type": ['Magic'], "effect": ['STEAL'],  } },
        { name: 'Fuzzy Cheeks', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['8'],  } },
        { name: 'Lucky Bucky', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['7'],  } },
        { name: 'Dodgy Dealer', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['9'],  } },
        { name: 'Tipsy Tootie', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['STEAL'], "Roll": ['6'],  } },
        { name: 'Peanut', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['7'],  } },
        { name: 'Mellow Dee', properties: {"type": ['Hero'], "hero": ['Bard'], "effect": ['DRAW'], "Roll": ['7'],  } },
        { name: 'Greedy Cheeks', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['8'],  } },
        { name: 'Napping Nibbles', properties: {"type": ['Hero'], "hero": ['Bard'], "Roll": ['2'],  } },
        { name: 'Tough Teddy', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['4'],  } },
        { name: 'Qi Bear', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD','DESTROY'], "Roll": ['10'],  } },
        { name: 'Heavy Bear', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['5'],  } },
        { name: 'Fury Knuckle', properties: {"type": ['Hero'], "hero": ['Fighter'], "Roll": ['5'],  } },
        { name: 'Bad Axe', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DESTROY'], "Roll": ['8'],  } },
        { name: 'Bear Claw', properties: {"type": ['Hero'], "hero": ['Fighter'], "Roll": ['7'],  } },
        { name: 'Pan Chucks', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DRAW','DESTROY'], "Roll": ['8'],  } },
        { name: 'Beary Wise', properties: {"type": ['Hero'], "hero": ['Fighter'], "effect": ['DISCARD'], "Roll": ['7'],  } },
        { name: 'Serious Grey', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DESTORY'], "Roll": ['9'],  } },
        { name: 'Sharp Fox', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['5'],  } },
        { name: 'Quick Draw', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['8'],  } },
        { name: 'Wildshot', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DAW','DISCARD'], "Roll": ['8'],  } },
        { name: 'Bullseye', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['7'],  } },
        { name: 'Lookie Rookie', properties: {"type": ['Hero'], "hero": ['Ranger'], "Roll": ['5'],  } },
        { name: 'Hook', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['6'],  } },
        { name: 'Wily Red', properties: {"type": ['Hero'], "hero": ['Ranger'], "effect": ['DRAW'], "Roll": ['10'],  } },
        { name: 'Smooth Mimimeow', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['7'],  } },
        { name: 'Meowzio', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['STEAL'], "Roll": ['10'],  } },
        { name: 'Sly Pickings', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['6'],  } },
        { name: 'Plundering Puma', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DRAW'], "Roll": ['6'],  } },
        { name: 'Shurikitty', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DESTORY'], "Roll": ['9'],  } },
        { name: 'Slippery Paws', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['DISCARD'], "Roll": ['6'],  } },
        { name: 'Silent Shadow', properties: {"type": ['Hero'], "hero": ['Thief'], "Roll": ['8'],  } },
        { name: 'Kit Napper', properties: {"type": ['Hero'], "hero": ['Thief'], "effect": ['STEAL'], "Roll": ['9'],  } },
        { name: 'Hopper', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['SACRIFICE'], "Roll": ['7'],  } },
        { name: 'Bun Bun', properties: {"type": ['Hero'], "hero": ['Wizard'], "Roll": ['5'],  } },
        { name: 'Spooky', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['SACRIFICE'], "Roll": ['10'],  } },
        { name: 'Buttons', properties: {"type": ['Hero'], "hero": ['Wizard'], "Roll": ['6'],  } },
        { name: 'Wiggles', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['STEAL'], "Roll": ['10'],  } },
        { name: 'Fluffy', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['DESTROY'], "Roll": ['10'],  } },
        { name: 'Snowball', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['DRAW'], "Roll": ['6'],  } },
        { name: 'Whiskers', properties: {"type": ['Hero'], "hero": ['Wizard'], "effect": ['STEAL','DESTROY'], "Roll": ['11'],  } },
        { name: 'Calming Voice', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['9'],  } },
        { name: 'Mighty Blade', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['8'],  } },
        { name: 'Vibrant Glow', properties: {"type": ['Hero'], "hero": ['Guardian'], "modifier": ['+'], "effect": ['MODIFIER'], "Roll": ['9'],  } },
        { name: 'Wise Shield', properties: {"type": ['Hero'], "hero": ['Guardian'], "modifier": ['+'], "effect": ['MODIFIER'], "Roll": ['6'],  } },
        { name: 'Iron Resolve', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['8'],  } },
        { name: 'Guiding Light', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['7'],  } },
        { name: 'Radiant Horn', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['6'],  } },
        { name: 'Holy Curselifter', properties: {"type": ['Hero'], "hero": ['Guardian'], "Roll": ['5'],  } },
    //   ],
    // },
    // {
    //   id: 2,
    //   name: 'Monster Cards',
    //   pick: 1,
    //   pickMax: 3,
    //   cards: [
    //     { name: 'Mega Slime', tags: ['4 Heroes'] },
    //     { name: 'Titan Wyvern', tags: ['2 Heroes', 'Fighter;Hero'] },
    //     { name: 'Orthus', tags: ['2 Heroes', 'Wizard;Hero'] },
    //     { name: 'Rex Major', tags: ['2 Heroes', 'Guardian;Hero'] },
    //     { name: 'Anuran Cauldron', tags: ['3 Heroes'] },
    //     { name: 'Terratuga', tags: ['1 Hero'] },
    //     { name: 'Artic Aries', tags: ['1 Hero'] },
    //     { name: 'Abyss Queen', tags: ['2 Heroes'] },
    //     { name: 'Corrupted Sabretooth', tags: ['3 Heroes'] },
    //     { name: 'Dark Dragon King', tags: ['2 Heroes', 'Bard;Hero'] },
    //     { name: 'Crowned Serpent', tags: ['2 Heroes'] },
    //     { name: 'Bloodwing', tags: ['2 Heroes'] },
    //     { name: 'Warworn Owlbear', tags: ['2 Heroes', 'Thief;Hero'] },
    //     { name: 'Dracos', tags: ['1 Hero'] },
    //     { name: 'Malamammoth', tags: ['2 Heroes', 'Ranger;Hero'] },
      ],
    },
    // {
    //   id: 1,
    //   name: 'Warriors & Druids',
    //   expansionId: 1,
    //   cards: [
    //     { name: 'Warrior', tags: ['Warrior;Hero'], count: 8 },
    //     { name: 'Warrior', tags: ['Druid;Hero'], count: 8 },
    //     { name: 'Challenge', tags: ['Challenge', 'Warrior;Hero'] },
    //     { name: 'Challenge', tags: ['Challenge', 'Druid;Hero'] },
    //     { name: 'Magic', tags: ['Magic'], count: 2 },
    //     { name: 'Cursed Item', tags: ['Item', 'Cursed'], count: 2 },
    //     { name: 'Item', tags: ['Item'], count: 5 },
    //     { name: 'Modifier +', tags: ['+;Modifier'] },
    //     { name: 'Modifier -', tags: ['-;Modifier'] },
    //     {
    //       name: 'Modifier +-',
    //       tags: ['+;Modifier', '-;Modifier'],
    //       count: 2,
    //     },
    //   ],
    // },
  ],
  diceSets: [
    {
      dice: [{ type: 'd6' }, { type: 'd6' }],
    },
  ],
};
