import { Game } from '../shared/models/game.model';

export const monopolyDealMetadata: Game = {
  minPlayers: 2,
  maxPlayers: 5,
  diceSets: [],
  decks: [
    {
      id: 1,
      pick: 2,
      cards: [
        { name: 'Baltic Avenue', properties: {"card": ['Property'], "color": ['Brown'], "value": ['1M'], "set size": ['2'],  } },
        { name: 'Mediterranean Avenue', properties: {"card": ['Property'], "color": ['Brown'], "value": ['1M'], "set size": ['2'],  } },
        { name: 'Vermont Avenue', properties: {"card": ['Property'], "color": ['Light Blue'], "value": ['1M'], "set size": ['3'],  } },
        { name: 'Connecticut Avenue', properties: {"card": ['Property'], "color": ['Light Blue'], "value": ['1M'], "set size": ['3'],  } },
        { name: 'Oriental Avenue', properties: {"card": ['Property'], "color": ['Light Blue'], "value": ['1M'], "set size": ['3'],  } },
        { name: 'Virginia Avenue', properties: {"card": ['Property'], "color": ['Pink'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'States Avenue', properties: {"card": ['Property'], "color": ['Pink'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'St. Charles Place', properties: {"card": ['Property'], "color": ['Pink'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'New York Avenue', properties: {"card": ['Property'], "color": ['Orange'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'Tennessee Avenue', properties: {"card": ['Property'], "color": ['Orange'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'St. James Place', properties: {"card": ['Property'], "color": ['Orange'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'Kentucky Avenue', properties: {"card": ['Property'], "color": ['Red'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Indiana Avenue', properties: {"card": ['Property'], "color": ['Red'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Illinois Avenue', properties: {"card": ['Property'], "color": ['Red'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Ventnor Avenue', properties: {"card": ['Property'], "color": ['Yellow'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Atlantic Avenue', properties: {"card": ['Property'], "color": ['Yellow'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Marvin Gardens', properties: {"card": ['Property'], "color": ['Yellow'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'North Caroline Avenue', properties: {"card": ['Property'], "color": ['Green'], "value": ['4M'], "set size": ['3'],  } },
        { name: 'Pennsylvania Avenue', properties: {"card": ['Property'], "color": ['Green'], "value": ['4M'], "set size": ['3'],  } },
        { name: 'Pacific Avenue', properties: {"card": ['Property'], "color": ['Green'], "value": ['4M'], "set size": ['3'],  } },
        { name: 'Park Place', properties: {"card": ['Property'], "color": ['Dark Blue'], "value": ['4M'], "set size": ['2'],  } },
        { name: 'Boardwalk', properties: {"card": ['Property'], "color": ['Dark Blue'], "value": ['4M'], "set size": ['2'],  } },
        { name: 'Reading Railroad', properties: {"card": ['Property'], "color": ['Railroad'], "value": ['2M'], "set size": ['4'],  } },
        { name: 'Short Line', properties: {"card": ['Property'], "color": ['Railroad'], "value": ['2M'], "set size": ['4'],  } },
        { name: 'Pennsylvania Railroad', properties: {"card": ['Property'], "color": ['Railroad'], "value": ['2M'], "set size": ['4'],  } },
        { name: 'B. & O. Railroad', properties: {"card": ['Property'], "color": ['Railroad'], "value": ['2M'], "set size": ['4'],  } },
        { name: 'Water Works', properties: {"card": ['Property'], "color": ['Utility'], "value": ['2M'], "set size": ['2'],  } },
        { name: 'Electric Company', properties: {"card": ['Property'], "color": ['Utility'], "value": ['2M'], "set size": ['2'],  } },
        { name: 'Property: Wild', properties: {"card": ['Property'], "color": ['Light Blue','Brown'], "value": ['1M'], "set size": ['3','2'],  } },
        { name: 'Property: Wild', properties: {"card": ['Property'], "color": ['Light Blue','Railroad'], "value": ['4M'], "set size": ['4','3'],  } },
        { name: 'Property: Wild', count: 2, properties: {"card": ['Property'], "color": ['Pink','Orange'], "value": ['2M'], "set size": ['3'],  } },
        { name: 'Property: Wild', count: 2, properties: {"card": ['Property'], "color": ['Red','Yellow'], "value": ['3M'], "set size": ['3'],  } },
        { name: 'Property: Wild', properties: {"card": ['Property'], "color": ['Dark Blue','Green'], "value": ['4M'], "set size": ['3','2'],  } },
        { name: 'Property: Wild', properties: {"card": ['Property'], "color": ['Green','Railroad'], "value": ['4M'], "set size": ['4','3'],  } },
        { name: 'Property: Wild', properties: {"card": ['Property'], "color": ['Railroad','Utility'], "value": ['2M'], "set size": ['4','2'],  } },
        { name: 'Property: Wild', count: 2, properties: {"card": ['Property'], "color": ['Brown','Light Blue','Pink','Orange','Red','Yellow','Green','Dark Blue','Railroad','Utility'], "set size": ['4','3','2'],  } },
        { name: 'Deal Breaker', count: 2, properties: {"card": ['Action'], "value": ['5M'],  } },
        { name: 'Forced Deal', count: 3, properties: {"card": ['Action'], "value": ['3M'],  } },
        { name: 'Sly Deal', count: 3, properties: {"card": ['Action'], "value": ['3M'],  } },
        { name: 'Just Say No!', count: 3, properties: {"card": ['Action'], "value": ['4M'],  } },
        { name: 'Debt Collector', count: 3, properties: {"card": ['Action'], "value": ['3M'],  } },
        { name: 'It\'s My Birthday', count: 3, properties: {"card": ['Action'], "value": ['2M'],  } },
        { name: 'Double The Rent', count: 2, properties: {"card": ['Action'], "value": ['1M'],  } },
        { name: 'House', count: 3, properties: {"card": ['Action'], "value": ['3M'],  } },
        { name: 'Hotel', count: 2, properties: {"card": ['Action'], "value": ['4M'],  } },
        { name: 'Pass Go', count: 10, properties: {"card": ['Action'], "value": ['1M'],  } },
        { name: 'Rent', count: 2, properties: {"card": ['Rent'], "color": ['Light Blue','Brown'], "value": ['1M'],  } },
        { name: 'Rent', count: 2, properties: {"card": ['Rent'], "color": ['Pink','Orange'], "value": ['1M'],  } },
        { name: 'Rent', count: 2, properties: {"card": ['Rent'], "color": ['Red','Yellow'], "value": ['1M'],  } },
        { name: 'Rent', count: 2, properties: {"card": ['Rent'], "color": ['Dark Blue','Green'], "value": ['1M'],  } },
        { name: 'Rent', count: 2, properties: {"card": ['Rent'], "color": ['Railroad','Utility'], "value": ['1M'],  } },
        { name: 'Rent: Wild', count: 3, properties: {"card": ['Rent'], "color": ['Brown','Light Blue','Pink','Orange','Red','Yellow','Green','Dark Blue','Railroad','Utility'], "value": ['3M'],  } },
        { name: '1M', count: 6, properties: {"card": ['Money'], "value": ['1M'],  } },
        { name: '2M', count: 5, properties: {"card": ['Money'], "value": ['2M'],  } },
        { name: '3M', count: 3, properties: {"card": ['Money'], "value": ['3M'],  } },
        { name: '4M', count: 3, properties: {"card": ['Money'], "value": ['4M'],  } },
        { name: '5M', count: 2, properties: {"card": ['Money'], "value": ['5M'],  } },
        { name: '10M', properties: {"card": ['Money'], "value": ['10M'],  } },
      ],
    },
  ],
  expansions: [],
};
