import { Game } from '../shared/models/game.model';

export const wingspanMetadata: Game = {
  minPlayers: 2,
  maxPlayers: 5,
  decks: [
    {
      id: 1,
      name: 'Main',
      pick: 1,
      pickMax: 3,
      cards: [
        { name: 'Acorn Woodpecker', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['4'], "food": ['Seed'], "victory points": ['5'], "wingspan": ['46'],  } },
        { name: 'American Avocet', properties: {"color": ['Pink'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['6'], "wingspan": ['79'],  } },
        { name: 'American Bittern', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish','Rodent'], "victory points": ['7'], "wingspan": ['107'],  } },
        { name: 'American Coot', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['5'], "food": ['Seed','Wild'], "victory points": ['3'], "wingspan": ['61'],  } },
        { name: 'American Crow', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Wild'], "victory points": ['4'], "wingspan": ['99'],  } },
        { name: 'American Goldfinch', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['23'],  } },
        { name: 'American Kestrel', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate','Rodent'], "victory points": ['5'], "wingspan": ['56'], "predator": ['Yes'],  } },
        { name: 'American Oystercatcher', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['81'],  } },
        { name: 'American Robin', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['43'],  } },
        { name: 'American White Pelican', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['1'], "food": ['Fish'], "victory points": ['5'], "wingspan": ['274'],  } },
        { name: 'American Woodcock', properties: {"color": ['None'], "nest": ['Ground'], "environment": ['Forest','Grassland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['9'], "wingspan": ['46'],  } },
        { name: 'Anhinga', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish'], "victory points": ['6'], "wingspan": ['114'], "predator": ['Yes'],  } },
        { name: 'Anna\'s Hummingbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Wild'], "victory points": ['4'], "wingspan": ['13'],  } },
        { name: 'Ash-Throated Flycatcher', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['30'],  } },
        { name: 'Atlantic Puffin', properties: {"color": ['White'], "nest": ['Wild'], "environment": ['Wetland'], "eggs": ['1'], "food": ['Fish'], "victory points": ['8'], "wingspan": ['53'],  } },
        { name: 'Baird\'s Sparrow', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['23'],  } },
        { name: 'Bald Eagle', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['1'], "food": ['Fish','Rodent'], "victory points": ['9'], "wingspan": ['203'],  } },
        { name: 'Baltimore Oriole', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['9'], "wingspan": ['30'],  } },
        { name: 'Barn Owl', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['4'], "food": ['Rodent'], "victory points": ['5'], "wingspan": ['107'], "predator": ['Yes'],  } },
        { name: 'Barn Swallow', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['38'],  } },
        { name: 'Barred Owl', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['3'], "wingspan": ['107'], "predator": ['Yes'],  } },
        { name: 'Barrow\'s Goldeneye', properties: {"color": ['Pink'], "nest": ['Cavity'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate','Seed','Fish'], "victory points": ['5'], "wingspan": ['71'],  } },
        { name: 'Bell\'s Vireo', properties: {"color": ['White'], "nest": ['Wild'], "environment": ['Forest','Grassland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['18'],  } },
        { name: 'Belted Kingfisher', properties: {"color": ['Pink'], "nest": ['Wild'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Fish','Wild'], "victory points": ['4'], "wingspan": ['53'],  } },
        { name: 'Bewick\'s Wren', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['18'],  } },
        { name: 'Black Skimmer', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish'], "victory points": ['6'], "wingspan": ['112'], "predator": ['Yes'],  } },
        { name: 'Black Tern', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['4'], "wingspan": ['61'],  } },
        { name: 'Black Vulture', properties: {"color": ['Pink'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['1'], "victory points": ['2'], "wingspan": ['150'],  } },
        { name: 'Black-Bellied Whistling Duck', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Wetland'], "eggs": ['5'], "food": ['Seed'], "victory points": ['2'], "wingspan": ['76'],  } },
        { name: 'Black-Billed Magpie', properties: {"color": ['Pink'], "nest": ['Wild'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Wild'], "victory points": ['3'], "wingspan": ['64'],  } },
        { name: 'Black-Crowned Night-Heron', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish','Rodent'], "victory points": ['9'], "wingspan": ['112'],  } },
        { name: 'Black-Necked Stilt', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['74'],  } },
        { name: 'Blue Grosbeak', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['28'],  } },
        { name: 'Blue Jay', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Seed','Wild'], "victory points": ['3'], "wingspan": ['41'],  } },
        { name: 'Blue-Gray Gnatcatcher', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['15'],  } },
        { name: 'Blue-Winged Warbler', properties: {"color": ['None'], "nest": ['Bowl'], "environment": ['Forest','Grassland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['8'], "wingspan": ['20'],  } },
        { name: 'Bobolink', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['30'],  } },
        { name: 'Brewer\'s Blackbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Seed','Wild'], "victory points": ['3'], "wingspan": ['41'],  } },
        { name: 'Bronzed Cowbird', properties: {"color": ['Pink'], "nest": ['None'], "environment": ['Grassland'], "eggs": ['0'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['36'],  } },
        { name: 'Brown Pelican', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish'], "victory points": ['4'], "wingspan": ['201'],  } },
        { name: 'Brown-Headed Cowbird', properties: {"color": ['Pink'], "nest": ['None'], "environment": ['Grassland'], "eggs": ['0'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['30'],  } },
        { name: 'Burrowing Owl', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Rodent'], "victory points": ['5'], "wingspan": ['53'], "predator": ['Yes'],  } },
        { name: 'Bushtit', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['5'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['15'],  } },
        { name: 'California Condor', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['1'], "victory points": ['1'], "wingspan": ['277'],  } },
        { name: 'California Quail', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland'], "eggs": ['6'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['36'],  } },
        { name: 'Canada Goose', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland','Wetland'], "eggs": ['3'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['132'],  } },
        { name: 'Carolina Chickadee', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['20'],  } },
        { name: 'Carolina Wren', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['5'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['20'],  } },
        { name: 'Cassin\'s Finch', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['3'], "food": ['Seed'], "victory points": ['4'], "wingspan": ['30'],  } },
        { name: 'Cassin\'s Sparrow', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['20'],  } },
        { name: 'Cedar Waxwing', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland'], "eggs": ['3'], "victory points": ['3'], "wingspan": ['25'],  } },
        { name: 'Cerulean Warbler', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['20'],  } },
        { name: 'Chestnut-Collared Longspur', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['25'],  } },
        { name: 'Chihuahuan Raven', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Rodent','Wild'], "victory points": ['4'], "wingspan": ['112'],  } },
        { name: 'Chimney Swift', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['36'],  } },
        { name: 'Chipping Sparrow', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['1'], "wingspan": ['23'],  } },
        { name: 'Clark\'s Grebe', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish'], "victory points": ['5'], "wingspan": ['61'],  } },
        { name: 'Clark\'s Nutcracker', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest'], "eggs": ['2'], "food": ['Seed','Wild'], "victory points": ['5'], "wingspan": ['61'],  } },
        { name: 'Common Grackle', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Seed','Wild'], "victory points": ['3'], "wingspan": ['43'],  } },
        { name: 'Common Loon', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['1'], "food": ['Fish','Wild'], "victory points": ['6'], "wingspan": ['117'],  } },
        { name: 'Common Merganser', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Fish','Wild'], "victory points": ['5'], "wingspan": ['86'], "predator": ['Yes'],  } },
        { name: 'Common Nighthawk', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['56'],  } },
        { name: 'Common Raven', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Rodent','Wild'], "victory points": ['5'], "wingspan": ['135'],  } },
        { name: 'Common Yellowthroat', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['18'],  } },
        { name: 'Cooper\'s Hawk', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['3'], "wingspan": ['79'], "predator": ['Yes'],  } },
        { name: 'Dark-Eyed Junco', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['23'],  } },
        { name: 'Dickcissel', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['25'],  } },
        { name: 'Double-Crested Cormorant', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['3'], "food": ['Fish','Wild'], "victory points": ['3'], "wingspan": ['132'],  } },
        { name: 'Downy Woodpecker', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['30'],  } },
        { name: 'Eastern Bluebird', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Grassland'], "eggs": ['5'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['33'],  } },
        { name: 'Eastern Kingbird', properties: {"color": ['Pink'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['2'], "wingspan": ['38'],  } },
        { name: 'Eastern Phoebe', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['28'],  } },
        { name: 'Eastern Screech Owl', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate','Rodent'], "victory points": ['4'], "wingspan": ['51'], "predator": ['Yes'],  } },
        { name: 'Ferruginous Hawk', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['6'], "wingspan": ['142'], "predator": ['Yes'],  } },
        { name: 'Fish Crow', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Fish','Wild'], "victory points": ['6'], "wingspan": ['91'],  } },
        { name: 'Forster\'s Tern', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['4'], "wingspan": ['79'],  } },
        { name: 'Franklin\'s Gull', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Grassland','Wetland'], "eggs": ['2'], "food": ['Fish','Wild'], "victory points": ['3'], "wingspan": ['91'],  } },
        { name: 'Golden Eagle', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland','Wetland'], "eggs": ['1'], "food": ['Rodent'], "victory points": ['8'], "wingspan": ['201'], "predator": ['Yes'],  } },
        { name: 'Grasshopper Sparrow', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['20'],  } },
        { name: 'Gray Catbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['28'],  } },
        { name: 'Great Blue Heron', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['5'], "wingspan": ['183'],  } },
        { name: 'Great Crested Flycatcher', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['33'],  } },
        { name: 'Great Egret', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['3'], "food": ['Fish','Rodent'], "victory points": ['7'], "wingspan": ['130'],  } },
        { name: 'Great Horned Owl', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['8'], "wingspan": ['112'], "predator": ['Yes'],  } },
        { name: 'Greater Prairie Chicken', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['71'],  } },
        { name: 'Greater Roadrunner', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate','Rodent','Wild'], "victory points": ['7'], "wingspan": ['56'], "predator": ['Yes'],  } }, 
        { name: 'Green Heron', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['3'], "food": ['Invertebrate','Fish'], "victory points": ['4'], "wingspan": ['66'],  } },
        { name: 'Hermit Thrush', properties: {"color": ['Brown'], "nest": ['Wild'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['7'], "wingspan": ['30'],  } },
        { name: 'Hooded Merganser', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate','Fish'], "victory points": ['5'], "wingspan": ['61'],  } },
        { name: 'Hooded Warbler', properties: {"color": ['None'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['7'], "wingspan": ['18'],  } },
        { name: 'Horned Lark', properties: {"color": ['Pink'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['30'],  } },
        { name: 'House Finch', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['6'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['25'],  } },
        { name: 'House Wren', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest','Grassland'], "eggs": ['5'], "food": ['Invertebrate'], "victory points": ['1'], "wingspan": ['15'],  } },
        { name: 'Inca Dove', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Seed'], "victory points": ['2'], "wingspan": ['28'],  } },
        { name: 'Indigo Bunting', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['20'],  } },
        { name: 'Juniper Titmouse', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['23'],  } },
        { name: 'Killdeer', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['1'], "wingspan": ['46'],  } },
        { name: 'King Rail', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['6'], "food": ['Invertebrate','Fish','Wild'], "victory points": ['4'], "wingspan": ['51'],  } },
        { name: 'Lazuli Bunting', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['23'],  } },
        { name: 'Lincoln\'s Sparrow', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['20'],  } },
        { name: 'Loggerhead Shrike', properties: {"color": ['Pink'], "nest": ['Bowl'], "environment": ['Grassland','Wetland'], "eggs": ['4'], "food": ['Invertebrate','Rodent'], "victory points": ['3'], "wingspan": ['30'],  } },
        { name: 'Mallard', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['0'], "wingspan": ['89'],  } },
        { name: 'Mississippi Kite', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland'], "eggs": ['1'], "food": ['Invertebrate','Rodent'], "victory points": ['4'], "wingspan": ['79'], "predator": ['Yes'],  } }, 
        { name: 'Mountain Bluebird', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Grassland'], "eggs": ['5'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['36'],  } },
        { name: 'Mountain Chickadee', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['23'],  } },
        { name: 'Mourning Dove', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['5'], "food": ['Seed'], "victory points": ['0'], "wingspan": ['46'],  } },
        { name: 'Northern Bobwhite', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['6'], "food": ['Seed'], "victory points": ['5'], "wingspan": ['33'],  } },
        { name: 'Northern Cardinal', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['5'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['30'],  } },
        { name: 'Northern Flicker', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest','Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['51'],  } },
        { name: 'Northern Harrier', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland','Wetland'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['3'], "wingspan": ['109'], "predator": ['Yes'],  } },
        { name: 'Northern Mockingbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['2'], "wingspan": ['36'],  } },
        { name: 'Northern Shoveler', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['7'], "wingspan": ['76'],  } },
        { name: 'Osprey', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish'], "victory points": ['5'], "wingspan": ['160'],  } },
        { name: 'Painted Bunting', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['5'], "wingspan": ['23'],  } },
        { name: 'Peregrine Falcon', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland','Wetland'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['5'], "wingspan": ['104'], "predator": ['Yes'],  } },
        { name: 'Pied-Billed Grebe', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate','Fish'], "victory points": ['0'], "wingspan": ['41'],  } },
        { name: 'Pileated Woodpecker', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['74'],  } },
        { name: 'Pine Siskin', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Seed'], "victory points": ['3'], "wingspan": ['23'],  } },
        { name: 'Prothonotary Warbler', properties: {"color": ['None'], "nest": ['Cavity'], "environment": ['Forest','Wetland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['8'], "wingspan": ['23'],  } },
        { name: 'Purple Gallinule', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Seed','Wild'], "victory points": ['7'], "wingspan": ['56'],  } },
        { name: 'Purple Martin', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['2'], "wingspan": ['46'],  } },
        { name: 'Pygmy Nuthatch', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['20'],  } },
        { name: 'Red Crossbill', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Seed'], "victory points": ['6'], "wingspan": ['28'],  } },
        { name: 'Red-Bellied Woodpecker', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['1'], "wingspan": ['41'],  } },
        { name: 'Red-Breasted Nuthatch', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['23'],  } },
        { name: 'Red-Cockaded Woodpecker', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['4'], "wingspan": ['36'],  } },
        { name: 'Red-Eyed Vireo', properties: {"color": ['White'], "nest": ['Wild'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['25'],  } },
        { name: 'Red-Headed Woodpecker', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate','Seed','Wild'], "victory points": ['4'], "wingspan": ['43'],  } },    
        { name: 'Red-Shouldered Hawk', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['3'], "wingspan": ['102'], "predator": ['Yes'],  } },
        { name: 'Red-Tailed Hawk', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Rodent'], "victory points": ['5'], "wingspan": ['124'], "predator": ['Yes'],  } },      
        { name: 'Red-Winged Blackbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Grassland','Wetland'], "eggs": ['3'], "food": ['Seed'], "victory points": ['2'], "wingspan": ['33'],  } },
        { name: 'Ring-Billed Gull', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Wild'], "victory points": ['4'], "wingspan": ['122'],  } },
        { name: 'Rose-Breasted Grosbeak', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['6'], "wingspan": ['33'],  } },
        { name: 'Roseate Spoonbill', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Seed','Fish'], "victory points": ['6'], "wingspan": ['127'],  } },
        { name: 'Ruby-Crowned Kinglet', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['20'],  } },
        { name: 'Ruby-Throated Hummingbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['2'], "food": ['Wild'], "victory points": ['4'], "wingspan": ['10'],  } },
        { name: 'Ruddy Duck', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['5'], "food": ['Invertebrate','Seed'], "victory points": ['0'], "wingspan": ['48'],  } },
        { name: 'Sandhill Crane', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland','Wetland'], "eggs": ['1'], "food": ['Seed','Wild'], "victory points": ['5'], "wingspan": ['196'],  } },
        { name: 'Savannah Sparrow', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['18'],  } },
        { name: 'Say\'s Phoebe', properties: {"color": ['White'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['33'],  } },
        { name: 'Scissor-Tailed Flycatcher', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['8'], "wingspan": ['38'],  } },
        { name: 'Snowy Egret', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['4'], "wingspan": ['104'], "predator": ['Yes'],  } },
        { name: 'Song Sparrow', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['5'], "food": ['Invertebrate','Seed'], "victory points": ['0'], "wingspan": ['20'],  } },
        { name: 'Spotted Owl', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['1'], "food": ['Rodent'], "victory points": ['5'], "wingspan": ['102'],  } },
        { name: 'Spotted Sandpiper', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['38'],  } },
        { name: 'Spotted Towhee', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['0'], "wingspan": ['28'],  } },
        { name: 'Sprague\'s Pipit', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['3'], "wingspan": ['25'],  } },
        { name: 'Steller\'s Jay', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Seed','Wild'], "victory points": ['5'], "wingspan": ['48'],  } },
        { name: 'Swainson\'s Hawk', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Grassland'], "eggs": ['2'], "food": ['Invertebrate','Rodent'], "victory points": ['5'], "wingspan": ['130'], "predator": ['Yes'],  } },
        { name: 'Tree Swallow', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Wetland'], "eggs": ['4'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['38'],  } },
        { name: 'Trumpeter Swan', properties: {"color": ['None'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Seed','Wild'], "victory points": ['9'], "wingspan": ['203'],  } },
        { name: 'Tufted Titmouse', properties: {"color": ['White'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['25'],  } },
        { name: 'Turkey Vulture', properties: {"color": ['Pink'], "nest": ['Cavity'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['1'], "victory points": ['1'], "wingspan": ['170'],  } },
        { name: 'Violet-Green Swallow', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['36'],  } },
        { name: 'Western Meadowlark', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Grassland'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['38'],  } },
        { name: 'Western Tanager', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['6'], "wingspan": ['30'],  } },
        { name: 'White-Breasted Nuthatch', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['28'],  } },
        { name: 'White-Crowned Sparrow', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['5'], "food": ['Invertebrate','Seed'], "victory points": ['2'], "wingspan": ['25'],  } },
        { name: 'White-Faced Ibis', properties: {"color": ['Brown'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['8'], "wingspan": ['91'], "predator": ['Yes'],  } },
        { name: 'Whooping Crane', properties: {"color": ['White'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['1'], "food": ['Wild'], "victory points": ['6'], "wingspan": ['221'],  } },
        { name: 'Wild Turkey', properties: {"color": ['None'], "nest": ['Ground'], "environment": ['Forest','Grassland'], "eggs": ['5'], "food": ['Seed'], "victory points": ['8'], "wingspan": ['135'],  } },
        { name: 'Willet', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate','Fish'], "victory points": ['4'], "wingspan": ['66'], "predator": ['Yes'],  } },
        { name: 'Wilson\'s Snipe', properties: {"color": ['Brown'], "nest": ['Ground'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['41'],  } },
        { name: 'Wood Duck', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest','Wetland'], "eggs": ['4'], "food": ['Seed'], "victory points": ['4'], "wingspan": ['76'],  } },
        { name: 'Wood Stork', properties: {"color": ['White'], "nest": ['Platform'], "environment": ['Wetland'], "eggs": ['2'], "food": ['Fish','Rodent','Wild'], "victory points": ['6'], "wingspan": ['155'],  } },
        { name: 'Yellow-Bellied Sapsucker', properties: {"color": ['Brown'], "nest": ['Cavity'], "environment": ['Forest'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['3'], "wingspan": ['41'],  } },
        { name: 'Yellow-Billed Cuckoo', properties: {"color": ['Pink'], "nest": ['Platform'], "environment": ['Forest'], "eggs": ['2'], "food": ['Invertebrate','Wild'], "victory points": ['5'], "wingspan": ['46'],  } },
        { name: 'Yellow-Breasted Chat', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest','Grassland','Wetland'], "eggs": ['3'], "food": ['Invertebrate'], "victory points": ['5'], "wingspan": ['25'],  } },
        { name: 'Yellow-Headed Blackbird', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Wetland'], "eggs": ['3'], "food": ['Invertebrate','Seed'], "victory points": ['4'], "wingspan": ['38'],  } },
        { name: 'Yellow-Rumped Warbler', properties: {"color": ['Brown'], "nest": ['Bowl'], "environment": ['Forest'], "eggs": ['4'], "food": ['Invertebrate','Seed'], "victory points": ['1'], "wingspan": ['23'],  } },
      ]
    }
  ],
  expansions: [],
  diceSets: [
    {
      dice: [
        { type: 'fancy', sides: ['Invertebrate (Worm)', 'Fruit', 'Fish', 'Seed', 'Rodent', ['Invertebrate (Worm)', 'Seed']], },
        { type: 'fancy', sides: ['Invertebrate (Worm)', 'Fruit', 'Fish', 'Seed', 'Rodent', ['Invertebrate (Worm)', 'Seed']], },
        { type: 'fancy', sides: ['Invertebrate (Worm)', 'Fruit', 'Fish', 'Seed', 'Rodent', ['Invertebrate (Worm)', 'Seed']], },
        { type: 'fancy', sides: ['Invertebrate (Worm)', 'Fruit', 'Fish', 'Seed', 'Rodent', ['Invertebrate (Worm)', 'Seed']], },
        { type: 'fancy', sides: ['Invertebrate (Worm)', 'Fruit', 'Fish', 'Seed', 'Rodent', ['Invertebrate (Worm)', 'Seed']], },
      ],
    },
  ],
};
